version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./themes/challecara:/var/www/html/wp-content/themes/challecara
      - ./index.html:/var/www/html/index.html
      - ./assets_top:/var/www/html/assets_top
      - ./index_2017.html:/var/www/html/index_2017.html
      - ./index_2016.html:/var/www/html/index_2016.html
      - ./.htaccess:/var/www/html/.htaccess

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - 'mysql:/var/lib/mysql'

volumes:
  mysql:
